hl.config({ autogenerated = false })

------------------
---- MONITORS ----
------------------

hl.monitor({
    output   = "HDMI-A-2",
    mode     = "1920x1080@100",
    position = "0x0",
    scale    = 1,
})


-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

hl.env("HYPRCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")


---------------------
---- AUTOSTART ----
---------------------

hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("mako")
    hl.exec_cmd("pipewire")
    hl.exec_cmd("wireplumber")
    hl.exec_cmd("pipewire-pulse")
end)


-----------------------
----- LOOK & FEEL -----
-----------------------

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 10,

        border_size = 0,

        col = {
            active_border = "rgba(33ccffee)",
            inactive_border = "rgba(595959aa)",
        },

        layout = "dwindle",
    },

    decoration = {
        rounding = 5,

        active_opacity = 1.0,
        inactive_opacity = 1.0,
    },

    animations = {
        enabled = true,
    },
})


--------------------
---- ANIMATIONS ----
--------------------

hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 7,
    bezier = "default"
})

hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 7,
    bezier = "default"
})

hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 6,
    bezier = "default"
})


----------------
---- INPUT ----
----------------

hl.config({
    input = {
        kb_layout = "pl",

        follow_mouse = 1,

        sensitivity = -0.30,
        accel_profile = "flat",

        touchpad = {
            natural_scroll = true,
        },
    },
})


---------------------
---- KEYBINDS ----
---------------------

local mod = "SUPER"

-- Programy

hl.bind(mod .. " + RETURN",
    hl.dsp.exec_cmd("kitty")
)

hl.bind(mod .. " + S",
    hl.dsp.exec_cmd("wofi --show drun")
)

hl.bind(mod .. " + Q",
    hl.dsp.window.close()
)

hl.bind(mod .. " + F",
    hl.dsp.window.fullscreen()
)

hl.bind(mod .. " + SHIFT + R",
    hl.dsp.exec_cmd("hyprctl dispatch exit")
)

hl.bind(mod .. " + SHIFT + S",
    hl.dsp.exec_cmd('grim -g "$(slurp -d)" - | wl-copy')
)


-- Workspaces

for i = 1,5 do
    hl.bind(
        mod .. " + " .. i,
        hl.dsp.focus({workspace = i})
    )

    hl.bind(
        mod .. " + SHIFT + " .. i,
        hl.dsp.window.move({workspace = i})
    )
end


-- Focus

hl.bind(mod .. " + left",
    hl.dsp.focus({direction="left"})
)

hl.bind(mod .. " + right",
    hl.dsp.focus({direction="right"})
)

hl.bind(mod .. " + up",
    hl.dsp.focus({direction="up"})
)

hl.bind(mod .. " + down",
    hl.dsp.focus({direction="down"})
)


-------------------------
---- WINDOW RULES -------
-------------------------

hl.window_rule({
    name = "suppress-maximize",
    match = {
        class = ".*"
    },
    suppress_event = "maximize",
})


----------------------
---- LAYOUT ----------
----------------------

hl.config({
    dwindle = {
        preserve_split = true,
    },
})
